export const GET_TASK="GET_TASK";

export const ADD_TASK_LOADING = "ADD_TASK_LOADING";
export const ADD_TASK_SUCCESS = "ADD_TASK_SUCCESS";
export const ADD_TASK_ERROR = "ADD_TASK_ERROR";

export const UPDATE_TASK_LOADING = "UPDATE_TASK_LOADING";
export const UPDATE_TASK_SUCCESS = "UPDATE_TASK_SUCCESS";
export const UPDATE_TASK_ERROR = "UPDATE_TASK_ERROR";

export const DELETE_TASK_LOADING = "DELETE_TASK_LOADING";
export const DELETE_TASK_SUCCESS = "DELETE_TASK_SUCCESS";
export const DELETE_TASK_ERROR = "DELETE_TASK_ERROR";


export const CLEAR_TASK_MESSAGE = "CLEAR_TASK_MESSAGE";